CREATE TABLE IF NOT EXISTS NOBLE_WIN (
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGROY TEXT
);

INSERT INTO NOBLE_WIN(YEAR,SUBJECT,WINNER,COUNTRY,CATEGROY) VALUES
(1970,'PHYSICS','SAM','ENGLAND','SCIENTIST'),
(1965,'LITERATURE','RAMU','INDIA','ECONOMIST'),
(1983,'CHEMISTRY','ARUN','USA','SCIENTIST'),
(1976,'PHYSIOLOGY','DAVID','GERMANY','SCIENTIST'),
(1966,'BIOLOGY','RAHUL','AUSTRALIA','SCIENTIST');

SELECT * FROM NOBLE_WIN WHERE SUBJECT NOT LIKE 'P%';