CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID TEXT,
    CUSTOMER_NAME TEXT,
    CUSTOMER_CITY TEXT,
    GRADE TEXT,
    SALESMAN_ID TEXT,
);

INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_CITY,GRADE,SALESMAN_ID)VALUES
('1','A','MUMBAI','a','10'),
('2','B','MUMBAI','a','20'),
('3','C','DELHI','b','30'),
('4','D','BHOPAL','b','40');

CREATE TABLE IF NOT EXISTS SALESMAN(
    SALESMAN_ID TEXT,PRIMARY KEY
    NAME TEXT,
    CITY TEXT,
    COMMISION TEXT,
);
INSERT INTO SALESMAN(SALESMAN_ID,NAME,CITY,COMMISSION)VALUES
('10','PATEL','MUMBAI','0.12'),
('20','RAHUL','MUMBAI','0.14'),
('30','VIRAJ','DELHI','0.13'),
('40','ROHIT','BHOPAL','0.12');

CREATE TABLE IF NOT EXISTS ORDER(
    ord_no TEXT
    ord_amt TEXT,
    ord_date TEXT,
    SALESMAN_ID TEXT,
    CUSTOMER_ID text,
);
INSERT INTO ORDER(ord_no,ord_amt,ord_date,SALESMAN_ID,CUSTOMER_ID)VALUES
('100','325','12-10-24','10','1'),
('101','250','11-10-24','20','2'),
('102','475','12-10-24','30','3'),
('103','300','11-10-24','40','4');
SELECT CUSTOMER.CUSTOMER_NAME,SALESMAN.SALESMAN_NAME,






